import { describe, it, expect } from "vitest";
import type { DecisionRecord } from "../src/generated/index.js";
import { health } from "../src/index.js";

/**
 * Acceptance criterion for issue #5: "one generated type consumed by one
 * passing test". `DecisionRecord` is generated by `pnpm typegen` from
 * schemas/decision-record.schema.json — nothing hand-writes it. The `pretest`
 * step runs typegen and `tsc -p tsconfig.test.json`, so if the generated type
 * were missing or renamed this test would fail to type-check before it ran.
 */
describe("generated types are consumed by the app", () => {
  it("a DecisionRecord value satisfies the generated type", () => {
    const dr: DecisionRecord = {
      id: "DR-2027-001",
      title: "Adopt the Phase 0 monorepo scaffold",
      proposer: "PORTFOLIO",
      reversibility_class: "R1",
      decision: "Scaffold the console skeleton, migrations, typegen, and test runner.",
      status: "approved",
    };
    expect(dr.id).toMatch(/^DR-\d{4}-\d+$/);
    expect(dr.reversibility_class).toBe("R1");
  });

  it("the skeleton health check reports ok", () => {
    expect(health()).toEqual({ status: "ok", service: "evolveos-console", phase: 0 });
  });
});
